---
env:
  browser: true
  es2021: true

extends:
  # - standard
  - eslint:recommended

parserOptions:
  ecmaVersion: latest
  sourceType: module

globals:
  browser: readonly
  chrome: readonly

rules:
  indent:
    - error
    - 2
    - SwitchCase: 1
  linebreak-style:
    - error
    - unix
  quotes:
    - error
    - single
  semi:
    - error
    - always
  space-before-function-paren: 0
